# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import mflix_pb2 as mflix__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in mflix_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FilmeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GerenciaFilmes = channel.unary_unary(
                '/mflix.FilmeService/GerenciaFilmes',
                request_serializer=mflix__pb2.FilmePedido.SerializeToString,
                response_deserializer=mflix__pb2.PedidoResposta.FromString,
                _registered_method=True)


class FilmeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GerenciaFilmes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FilmeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GerenciaFilmes': grpc.unary_unary_rpc_method_handler(
                    servicer.GerenciaFilmes,
                    request_deserializer=mflix__pb2.FilmePedido.FromString,
                    response_serializer=mflix__pb2.PedidoResposta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mflix.FilmeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mflix.FilmeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FilmeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GerenciaFilmes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mflix.FilmeService/GerenciaFilmes',
            mflix__pb2.FilmePedido.SerializeToString,
            mflix__pb2.PedidoResposta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
