# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mflix.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'mflix.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmflix.proto\x12\x10org.example.grpc\"u\n\x05\x46ilme\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06titulo\x18\x02 \x01(\t\x12\x11\n\tdiretores\x18\x03 \x03(\t\x12\x0b\n\x03\x61no\x18\x04 \x01(\x05\x12\x0e\n\x06\x61tores\x18\x05 \x03(\t\x12\x0f\n\x07generos\x18\x06 \x03(\t\x12\x0f\n\x07\x64uracao\x18\x07 \x01(\x05\"\xcc\x01\n\x0b\x46ilmePedido\x12>\n\x0ftipo_requisicao\x18\x01 \x01(\x0e\x32%.org.example.grpc.FilmePedido.reqType\x12&\n\x05\x66ilme\x18\x02 \x01(\x0b\x32\x17.org.example.grpc.Filme\x12\x0e\n\x06\x61tores\x18\x03 \x03(\t\x12\x0f\n\x07generos\x18\x04 \x03(\t\"4\n\x07reqType\x12\x07\n\x03GET\x10\x00\x12\x08\n\x04POST\x10\x01\x12\n\n\x06UPDATE\x10\x02\x12\n\n\x06\x44\x45LETE\x10\x03\"\\\n\x0ePedidoResposta\x12\'\n\x06\x66ilmes\x18\x01 \x03(\x0b\x32\x17.org.example.grpc.Filme\x12\x10\n\x08mensagem\x18\x02 \x01(\t\x12\x0f\n\x07sucesso\x18\x03 \x01(\x08\x32\x61\n\x0c\x46ilmeService\x12Q\n\x0eGerenciaFilmes\x12\x1d.org.example.grpc.FilmePedido\x1a .org.example.grpc.PedidoRespostaB\x14\n\x10org.example.grpcP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mflix_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020org.example.grpcP\001'
  _globals['_FILME']._serialized_start=33
  _globals['_FILME']._serialized_end=150
  _globals['_FILMEPEDIDO']._serialized_start=153
  _globals['_FILMEPEDIDO']._serialized_end=357
  _globals['_FILMEPEDIDO_REQTYPE']._serialized_start=305
  _globals['_FILMEPEDIDO_REQTYPE']._serialized_end=357
  _globals['_PEDIDORESPOSTA']._serialized_start=359
  _globals['_PEDIDORESPOSTA']._serialized_end=451
  _globals['_FILMESERVICE']._serialized_start=453
  _globals['_FILMESERVICE']._serialized_end=550
# @@protoc_insertion_point(module_scope)
