# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mflix.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmflix.proto\x12\x05mflix\"u\n\x05\x46ilme\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06titulo\x18\x02 \x01(\t\x12\x11\n\tdiretores\x18\x03 \x03(\t\x12\x0b\n\x03\x61no\x18\x04 \x01(\x05\x12\x0e\n\x06\x61tores\x18\x05 \x03(\t\x12\x0f\n\x07generos\x18\x06 \x03(\t\x12\x0f\n\x07\x64uracao\x18\x07 \x01(\x05\"\xb6\x01\n\x0b\x46ilmePedido\x12\x33\n\x0ftipo_requisicao\x18\x01 \x01(\x0e\x32\x1a.mflix.FilmePedido.reqType\x12\x1b\n\x05\x66ilme\x18\x02 \x01(\x0b\x32\x0c.mflix.Filme\x12\x0e\n\x06\x61tores\x18\x03 \x03(\t\x12\x0f\n\x07generos\x18\x04 \x03(\t\"4\n\x07reqType\x12\x07\n\x03GET\x10\x00\x12\x08\n\x04POST\x10\x01\x12\n\n\x06UPDATE\x10\x02\x12\n\n\x06\x44\x45LETE\x10\x03\"Q\n\x0ePedidoResposta\x12\x1c\n\x06\x66ilmes\x18\x01 \x03(\x0b\x32\x0c.mflix.Filme\x12\x10\n\x08mensagem\x18\x02 \x01(\t\x12\x0f\n\x07sucesso\x18\x03 \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mflix_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FILME._serialized_start=22
  _FILME._serialized_end=139
  _FILMEPEDIDO._serialized_start=142
  _FILMEPEDIDO._serialized_end=324
  _FILMEPEDIDO_REQTYPE._serialized_start=272
  _FILMEPEDIDO_REQTYPE._serialized_end=324
  _PEDIDORESPOSTA._serialized_start=326
  _PEDIDORESPOSTA._serialized_end=407
# @@protoc_insertion_point(module_scope)
