syntax = "proto3";

package mflix;

message Filme {
    string id = 1;
    string titulo = 2;
    repeated string diretores = 3;
    int32 ano = 4;
    repeated string atores = 5;
    repeated string generos = 6;
    int32 duracao = 7;
}

message FilmePedido {
    enum reqType {
        GET = 1;
        POST = 2;
        UPDATE = 3;
        DELETE = 4;
    }
    reqType tipo_requisicao = 1;
    Filme filme = 2;
    repeated string atores = 3;
    repeated string generos = 4;
}

message PedidoResposta {
    repeated Filme filmes = 1;
    string mensagem = 2;
    bool sucesso = 3;
}

